"""food and category

Revision ID: 002_food_category
Revises: 001_init_user
Create Date: 2023-07-24 21:13:34.753966

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "002_food_category"
down_revision = "001_init_user"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "food_item.py",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "food_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("price", sa.DECIMAL(), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["food_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("food_item")
    op.drop_table("food_category")
    # ### end Alembic commands ###
